// 10 themes for iNwe Quo Pro v1
// Each theme defines CSS variable overrides applied via a <style> tag at runtime.

export interface Theme {
  id: string
  name: string
  icon: string
  vars: Record<string, string>
}

export const THEMES: Theme[] = [
  {
    id: 'light',
    name: 'Light',
    icon: '☀',
    vars: {
      '--background': '#f5f5f0',
      '--foreground': '#1a1a1a',
      '--card': '#ffffff',
      '--card-foreground': '#1a1a1a',
      '--popover': '#ffffff',
      '--popover-foreground': '#1a1a1a',
      '--primary': '#0066cc',
      '--primary-foreground': '#ffffff',
      '--secondary': '#e8e8e0',
      '--secondary-foreground': '#1a1a1a',
      '--muted': '#f0f0e8',
      '--muted-foreground': '#666666',
      '--accent': '#e8e8e0',
      '--accent-foreground': '#0066cc',
      '--destructive': '#cc0000',
      '--border': '#999999',
      '--input': '#ffffff',
      '--ring': '#0066cc',
      '--header-bg': '#e8e8e0',
      '--header-text': '#0066cc',
      '--footer-bg': '#e8e8e0',
      '--footer-text': '#666666',
    },
  },
  {
    id: 'dark',
    name: 'Dark',
    icon: '🌙',
    vars: {
      '--background': '#0a0a0a',
      '--foreground': '#d4d4d4',
      '--card': '#141414',
      '--card-foreground': '#d4d4d4',
      '--popover': '#141414',
      '--popover-foreground': '#d4d4d4',
      '--primary': '#7cfc00',
      '--primary-foreground': '#0a0a0a',
      '--secondary': '#1f1f1f',
      '--secondary-foreground': '#d4d4d4',
      '--muted': '#1a1a1a',
      '--muted-foreground': '#888888',
      '--accent': '#1f1f1f',
      '--accent-foreground': '#7cfc00',
      '--destructive': '#e41e3f',
      '--border': '#333333',
      '--input': '#1a1a1a',
      '--ring': '#7cfc00',
      '--header-bg': '#1a1a1a',
      '--header-text': '#7cfc00',
      '--footer-bg': '#1a1a1a',
      '--footer-text': '#888888',
    },
  },
  {
    id: 'ocean',
    name: 'Ocean',
    icon: '🌊',
    vars: {
      '--background': '#0d1b2a',
      '--foreground': '#e0e1dd',
      '--card': '#1b263b',
      '--card-foreground': '#e0e1dd',
      '--popover': '#1b263b',
      '--popover-foreground': '#e0e1dd',
      '--primary': '#4cc9f0',
      '--primary-foreground': '#0d1b2a',
      '--secondary': '#243447',
      '--secondary-foreground': '#e0e1dd',
      '--muted': '#1b263b',
      '--muted-foreground': '#778da9',
      '--accent': '#243447',
      '--accent-foreground': '#4cc9f0',
      '--destructive': '#ef476f',
      '--border': '#415a77',
      '--input': '#1b263b',
      '--ring': '#4cc9f0',
      '--header-bg': '#1b263b',
      '--header-text': '#4cc9f0',
      '--footer-bg': '#1b263b',
      '--footer-text': '#778da9',
    },
  },
  {
    id: 'sunset',
    name: 'Sunset',
    icon: '🌅',
    vars: {
      '--background': '#fff5eb',
      '--foreground': '#3d1e0a',
      '--card': '#ffffff',
      '--card-foreground': '#3d1e0a',
      '--popover': '#ffffff',
      '--popover-foreground': '#3d1e0a',
      '--primary': '#e8590c',
      '--primary-foreground': '#ffffff',
      '--secondary': '#ffe8cc',
      '--secondary-foreground': '#3d1e0a',
      '--muted': '#fff0e0',
      '--muted-foreground': '#8a5a2b',
      '--accent': '#ffe8cc',
      '--accent-foreground': '#e8590c',
      '--destructive': '#c92a2a',
      '--border': '#ffa94d',
      '--input': '#ffffff',
      '--ring': '#e8590c',
      '--header-bg': '#ffe8cc',
      '--header-text': '#e8590c',
      '--footer-bg': '#ffe8cc',
      '--footer-text': '#8a5a2b',
    },
  },
  {
    id: 'forest',
    name: 'Forest',
    icon: '🌲',
    vars: {
      '--background': '#f0f4ec',
      '--foreground': '#1a2e1a',
      '--card': '#ffffff',
      '--card-foreground': '#1a2e1a',
      '--popover': '#ffffff',
      '--popover-foreground': '#1a2e1a',
      '--primary': '#2b8a3e',
      '--primary-foreground': '#ffffff',
      '--secondary': '#d3e4cd',
      '--secondary-foreground': '#1a2e1a',
      '--muted': '#e8f0e2',
      '--muted-foreground': '#4a6a4a',
      '--accent': '#d3e4cd',
      '--accent-foreground': '#2b8a3e',
      '--destructive': '#c92a2a',
      '--border': '#82c91e',
      '--input': '#ffffff',
      '--ring': '#2b8a3e',
      '--header-bg': '#d3e4cd',
      '--header-text': '#2b8a3e',
      '--footer-bg': '#d3e4cd',
      '--footer-text': '#4a6a4a',
    },
  },
  {
    id: 'purple',
    name: 'Purple Rain',
    icon: '🟣',
    vars: {
      '--background': '#1a0a2e',
      '--foreground': '#e0d4f5',
      '--card': '#2a1a3e',
      '--card-foreground': '#e0d4f5',
      '--popover': '#2a1a3e',
      '--popover-foreground': '#e0d4f5',
      '--primary': '#a855f7',
      '--primary-foreground': '#1a0a2e',
      '--secondary': '#3a2a4e',
      '--secondary-foreground': '#e0d4f5',
      '--muted': '#2a1a3e',
      '--muted-foreground': '#9b8ab5',
      '--accent': '#3a2a4e',
      '--accent-foreground': '#a855f7',
      '--destructive': '#ef476f',
      '--border': '#6b3fa0',
      '--input': '#2a1a3e',
      '--ring': '#a855f7',
      '--header-bg': '#2a1a3e',
      '--header-text': '#a855f7',
      '--footer-bg': '#2a1a3e',
      '--footer-text': '#9b8ab5',
    },
  },
  {
    id: 'rose',
    name: 'Rose',
    icon: '🌹',
    vars: {
      '--background': '#fff5f7',
      '--foreground': '#2e0a1a',
      '--card': '#ffffff',
      '--card-foreground': '#2e0a1a',
      '--popover': '#ffffff',
      '--popover-foreground': '#2e0a1a',
      '--primary': '#e91e63',
      '--primary-foreground': '#ffffff',
      '--secondary': '#ffd6e0',
      '--secondary-foreground': '#2e0a1a',
      '--muted': '#ffe8ec',
      '--muted-foreground': '#8a4a5a',
      '--accent': '#ffd6e0',
      '--accent-foreground': '#e91e63',
      '--destructive': '#c92a2a',
      '--border': '#ff80ab',
      '--input': '#ffffff',
      '--ring': '#e91e63',
      '--header-bg': '#ffd6e0',
      '--header-text': '#e91e63',
      '--footer-bg': '#ffd6e0',
      '--footer-text': '#8a4a5a',
    },
  },
  {
    id: 'midnight',
    name: 'Midnight',
    icon: '🌃',
    vars: {
      '--background': '#0a0e27',
      '--foreground': '#c5cae9',
      '--card': '#151b3b',
      '--card-foreground': '#c5cae9',
      '--popover': '#151b3b',
      '--popover-foreground': '#c5cae9',
      '--primary': '#5c6bc0',
      '--primary-foreground': '#0a0e27',
      '--secondary': '#1a2347',
      '--secondary-foreground': '#c5cae9',
      '--muted': '#151b3b',
      '--muted-foreground': '#7986cb',
      '--accent': '#1a2347',
      '--accent-foreground': '#5c6bc0',
      '--destructive': '#ef5350',
      '--border': '#3949ab',
      '--input': '#151b3b',
      '--ring': '#5c6bc0',
      '--header-bg': '#151b3b',
      '--header-text': '#5c6bc0',
      '--footer-bg': '#151b3b',
      '--footer-text': '#7986cb',
    },
  },
  {
    id: 'amber',
    name: 'Amber',
    icon: '🍯',
    vars: {
      '--background': '#1c1407',
      '--foreground': '#f5e6c8',
      '--card': '#2a1f0c',
      '--card-foreground': '#f5e6c8',
      '--popover': '#2a1f0c',
      '--popover-foreground': '#f5e6c8',
      '--primary': '#ffc107',
      '--primary-foreground': '#1c1407',
      '--secondary': '#3a2f14',
      '--secondary-foreground': '#f5e6c8',
      '--muted': '#2a1f0c',
      '--muted-foreground': '#b8a070',
      '--accent': '#3a2f14',
      '--accent-foreground': '#ffc107',
      '--destructive': '#ff6f00',
      '--border': '#8d6e15',
      '--input': '#2a1f0c',
      '--ring': '#ffc107',
      '--header-bg': '#2a1f0c',
      '--header-text': '#ffc107',
      '--footer-bg': '#2a1f0c',
      '--footer-text': '#b8a070',
    },
  },
  {
    id: 'mono',
    name: 'Mono',
    icon: '◾',
    vars: {
      '--background': '#ffffff',
      '--foreground': '#000000',
      '--card': '#f8f8f8',
      '--card-foreground': '#000000',
      '--popover': '#f8f8f8',
      '--popover-foreground': '#000000',
      '--primary': '#000000',
      '--primary-foreground': '#ffffff',
      '--secondary': '#e0e0e0',
      '--secondary-foreground': '#000000',
      '--muted': '#f0f0f0',
      '--muted-foreground': '#666666',
      '--accent': '#e0e0e0',
      '--accent-foreground': '#000000',
      '--destructive': '#cc0000',
      '--border': '#cccccc',
      '--input': '#f8f8f8',
      '--ring': '#000000',
      '--header-bg': '#f0f0f0',
      '--header-text': '#000000',
      '--footer-bg': '#f0f0f0',
      '--footer-text': '#666666',
    },
  },
]

export const DEFAULT_THEME_ID = 'light'

export function getTheme(id: string): Theme {
  return THEMES.find(t => t.id === id) ?? THEMES[0]
}
